#!/bin/sh
rm -f /etc/apache2/mods-enabled/mod_trell.load
rm -f /etc/apache2/mods-enabled/mod_trell.conf

rm -f /etc/apache2/mods-available/mod_trell.load
rm -f /etc/apache2/mods-available/mod_trell.conf
service apache2 restart
rm -rf /usr/var/trell
